#! /bin/sh

# Make sure to run this script not as root as the script will ask for your password when it needs it


# installs DWM 
echo "Installing DWM enter your password"
sudo make install

#moves scripts for dwm and dwmblocks
echo "Moving scripts for dwmblocks and other scripts"
cp -rf .dwm ~/
cp -rf scripts/bin/ ~/.local/

#installs dwmblocks-async
echo "Installing dwmblocks-async"
cd dwmblocks-async
sudo make install
